import Head from 'next/head'
import Navigation from '../komponenten/Navigation'
import Fusszeile from '../komponenten/Fusszeile'
import { Children } from 'react'


export default function Layout({children}) {
  return (
    <div>
      <Head>
        <title>Liefer Meister - Dein Lieferservice</title>
        <meta name='description' content='Generated by virtualdev.de'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <Navigation/>
      <div className='container'>
      {children}
      </div>
      <Fusszeile/>
    </div>
  )
}
